# -*- coding: utf-8 -*-
"""
Program to plot the image arrays generated by Nucleus_w_condensates_sim.py
Saves both the No_condensates and W_condensates timeseries as .tif files
Author: Lydia Hodgins
"""
#Import Packages

import numpy as np
import matplotlib.pyplot as plt
import tifffile

#Define the folder the image arrays are saved in

foldername = 'C:/Users/Lydia/OneDrive/OneDrive - McMaster University/Documents/Summer Research Project/rerun_simulation/rerun_sim_trial3/'
for i in range(20):
    filename = 'frame'+ str(i) + '_image_array_no_condensate_2_pop.txt'
    data_file= foldername + filename
    
    image_intensities_no_condensate = np.loadtxt(   #import the image array without the condensate
        data_file,
        skiprows = 1)
    
    minvalue = np.min([np.min(image_intensities_no_condensate)]) 
    maxvalue = np.max([np.max(image_intensities_no_condensate)])
    
    #find minimum and maximum intensity values of the image arrays to set the scale of the color bar
    
    #plot the image with no condensate
    
    fig = plt.figure(figsize=(4.27,3.2))
    ax = plt.axes()
    
    im = plt.imshow(image_intensities_no_condensate, vmin=minvalue, vmax=maxvalue, cmap ='Greys_r')
    
    #plt.xlabel('x (pixels)', fontsize=14)
    #plt.ylabel('y (pixels)', fontsize=14)
    #plt.title('frame' +str(i) +', no condensate')
    #cbar = fig.colorbar(im, ax= ax)
    #cbar.ax.set_ylabel('Intensity (Photons/pixel)', fontsize=14)
    plt.axis('off')
    imagename = 'tif_files\\frame'+ str(i) + '_image_array_no_condensate_2_pop.tiff'
    file = foldername + imagename
    #plt.savefig(file,  bbox_inches='tight', pad_inches = 0)
    
    tifffile.imsave(file, image_intensities_no_condensate)
    
for i in range(20): #loop for plotting the multiple trials
    
    #plot the image with the condensate
    filename = 'frame'+ str(i) +'_image_array_w_condensate_2_pop.txt'
    data_file= foldername + filename
    
    image_intensities_w_condensate = np.loadtxt(    #import the image array with the condensate
        data_file,
        skiprows = 1)
    minvalue = np.min([np.min(image_intensities_w_condensate)]) 
    maxvalue = np.max([np.max(image_intensities_w_condensate)])
    
    
    fig = plt.figure(figsize=(4.27,3.2))
    ax = plt.axes()
    
    im = plt.imshow(image_intensities_w_condensate, vmin=minvalue, vmax=maxvalue, cmap ='Greys_r')
    
    #plt.xlabel('x (pixels)', fontsize=14)
    #plt.ylabel('y (pixels)', fontsize=14)
    #plt.title('frame' + str(i) +', w/ condensate')
    #cbar = fig.colorbar(im, ax= ax)
    #cbar.ax.set_ylabel('Intensity (Photons/pixel)', fontsize=14)
    plt.axis('off')
    imagename = 'tif_files\\frame'+ str(i) +'_image_array_w_condensate_2_pop.tiff'
    file = foldername + imagename
    #plt.savefig(file, bbox_inches='tight', pad_inches = 0)
    
    tifffile.imsave(file, image_intensities_w_condensate)
